"""Operational inventory API operations."""

from .activate_emergency_access_user import OPERATION as ACTIVATE_EMERGENCY_ACCESS_USER
from .create_emergency_access_user import OPERATION as CREATE_EMERGENCY_ACCESS_USER
from .create_privileged_approval import OPERATION as CREATE_PRIVILEGED_APPROVAL
from .deactivate_emergency_access_user import OPERATION as DEACTIVATE_EMERGENCY_ACCESS_USER
from .delete_expired_privileged_approvals import OPERATION as DELETE_EXPIRED_PRIVILEGED_APPROVALS
from .delete_private_cloud_controller import OPERATION as DELETE_PRIVATE_CLOUD_CONTROLLER
from .delete_privileged_approval import OPERATION as DELETE_PRIVILEGED_APPROVAL
from .get_emergency_access_user import OPERATION as GET_EMERGENCY_ACCESS_USER
from .get_private_cloud_controller import OPERATION as GET_PRIVATE_CLOUD_CONTROLLER
from .get_privileged_approval import OPERATION as GET_PRIVILEGED_APPROVAL
from .list_emergency_access_users import OPERATION as LIST_EMERGENCY_ACCESS_USERS
from .list_private_cloud_controllers import OPERATION as LIST_PRIVATE_CLOUD_CONTROLLERS
from .list_privileged_approvals import OPERATION as LIST_PRIVILEGED_APPROVALS
from .update_emergency_access_user import OPERATION as UPDATE_EMERGENCY_ACCESS_USER
from .update_private_cloud_controller import OPERATION as UPDATE_PRIVATE_CLOUD_CONTROLLER
from .update_privileged_approval import OPERATION as UPDATE_PRIVILEGED_APPROVAL

OPERATIONS = (
    LIST_PRIVATE_CLOUD_CONTROLLERS,
    GET_PRIVATE_CLOUD_CONTROLLER,
    UPDATE_PRIVATE_CLOUD_CONTROLLER,
    DELETE_PRIVATE_CLOUD_CONTROLLER,
    LIST_EMERGENCY_ACCESS_USERS,
    GET_EMERGENCY_ACCESS_USER,
    CREATE_EMERGENCY_ACCESS_USER,
    UPDATE_EMERGENCY_ACCESS_USER,
    ACTIVATE_EMERGENCY_ACCESS_USER,
    DEACTIVATE_EMERGENCY_ACCESS_USER,
    LIST_PRIVILEGED_APPROVALS,
    GET_PRIVILEGED_APPROVAL,
    CREATE_PRIVILEGED_APPROVAL,
    UPDATE_PRIVILEGED_APPROVAL,
    DELETE_PRIVILEGED_APPROVAL,
    DELETE_EXPIRED_PRIVILEGED_APPROVALS,
)

__all__ = [
    "ACTIVATE_EMERGENCY_ACCESS_USER",
    "CREATE_EMERGENCY_ACCESS_USER",
    "CREATE_PRIVILEGED_APPROVAL",
    "DEACTIVATE_EMERGENCY_ACCESS_USER",
    "DELETE_EXPIRED_PRIVILEGED_APPROVALS",
    "DELETE_PRIVATE_CLOUD_CONTROLLER",
    "DELETE_PRIVILEGED_APPROVAL",
    "GET_EMERGENCY_ACCESS_USER",
    "GET_PRIVATE_CLOUD_CONTROLLER",
    "GET_PRIVILEGED_APPROVAL",
    "LIST_EMERGENCY_ACCESS_USERS",
    "LIST_PRIVATE_CLOUD_CONTROLLERS",
    "LIST_PRIVILEGED_APPROVALS",
    "OPERATIONS",
    "UPDATE_EMERGENCY_ACCESS_USER",
    "UPDATE_PRIVATE_CLOUD_CONTROLLER",
    "UPDATE_PRIVILEGED_APPROVAL",
]
